enable-magisk-update = true
parallel-jobs = 1


#Stable
[YouTube-Extended-anddea]
release-name = "YT-RVX-anddea"
app-name="YouTube"
rv-brand = "ReVanced Extended anddea"
enabled = true
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "yt-rvx-anddea"
arch = "all"

[YouTube-Music-Extended-anddea]
release-name = "YT-Music-RVX-anddea"
app-name="YouTube Music"
rv-brand = "ReVanced Extended anddea"
enabled = true
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
module-prop-name = "ytm-rvx-anddea"
arch = "both"

[YouTube-Morphe]
release-name = "YT-Morphe"
app-name="YouTube"
rv-brand = "Morphe"
enabled = true
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "yt-morphe"
arch = "all"

[YouTube-Music-Morphe]
release-name = "YT-Music-Morphe"
app-name="YouTube Music"
rv-brand = "Morphe"
enabled = true
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
module-prop-name = "ytm-morphe"
arch = "both"

[Reddit-Morphe]
release-name = "Reddit-Morphe"
app-name="Reddit"
rv-brand = "Morphe"
enabled = true
version = "auto"
patches-source = "wchill/patcheddit"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
module-prop-name = "reddit-morphe"
arch = "all"
