enable-magisk-update = true
parallel-jobs = 1


#Stable
[YouTube-Extended-anddea]
enabled = true
release-name = "YT-RVX-anddea"
app-name="YouTube"
rv-brand = "ReVanced Extended anddea"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "yt-rvx-anddea"
arch = "all"

[YouTube-Music-Extended-anddea]
enabled = true
release-name = "YT-Music-RVX-anddea"
app-name="YouTube Music"
rv-brand = "ReVanced Extended anddea"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
module-prop-name = "ytm-rvx-anddea"
arch = "both"

[YouTube-Morphe]
enabled = true
release-name = "YT-Morphe"
app-name="YouTube"
rv-brand = "Morphe"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "yt-morphe"
arch = "all"

[YouTube-Music-Morphe]
enabled = true
release-name = "YT-Music-Morphe"
app-name="YouTube Music"
rv-brand = "Morphe"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
module-prop-name = "ytm-morphe"
arch = "both"

[Reddit-Morphe]
enabled = true
release-name = "Reddit-Morphe"
app-name = "Reddit"
rv-brand = "Morphe"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
module-prop-name = "reddit-morphe"
arch = "all"

[TikTok-DeRevanced]
enabled = true
release-name = "TikTok-DeRV"
app-name="TikTok"
rv-brand = "De-ReVanced"
version = "auto"
patches-source = "RookieEnough/De-Revanced"
cli-source = "MorpheApp/morphe-cli"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
module-prop-name = "tiktok-derevanced"
arch = "all"

[Twitch-DeRevanced]
enabled = true
release-name = "Twitch-DeRV"
app-name="Twitch"
rv-brand = "De-ReVanced"
version = "auto"
patches-source = "RookieEnough/De-Revanced"
cli-source = "MorpheApp/morphe-cli"
#apkmirror-dlurl = ""
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
module-prop-name = "twitch-derevanced"
arch = "all"
